// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/channels.proto

package BaLa071

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChannelServiceClient is the client API for ChannelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChannelServiceClient interface {
	AddChannel(ctx context.Context, in *AddChannelReq, opts ...grpc.CallOption) (*ViewChannelRes, error)
	ViewChannel(ctx context.Context, in *ChanReq, opts ...grpc.CallOption) (*ViewChannelRes, error)
	ListChannel(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*ListChannelRes, error)
}

type channelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelServiceClient(cc grpc.ClientConnInterface) ChannelServiceClient {
	return &channelServiceClient{cc}
}

func (c *channelServiceClient) AddChannel(ctx context.Context, in *AddChannelReq, opts ...grpc.CallOption) (*ViewChannelRes, error) {
	out := new(ViewChannelRes)
	err := c.cc.Invoke(ctx, "/channels.ChannelService/AddChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) ViewChannel(ctx context.Context, in *ChanReq, opts ...grpc.CallOption) (*ViewChannelRes, error) {
	out := new(ViewChannelRes)
	err := c.cc.Invoke(ctx, "/channels.ChannelService/ViewChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) ListChannel(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*ListChannelRes, error) {
	out := new(ListChannelRes)
	err := c.cc.Invoke(ctx, "/channels.ChannelService/ListChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelServiceServer is the server API for ChannelService service.
// All implementations must embed UnimplementedChannelServiceServer
// for forward compatibility
type ChannelServiceServer interface {
	AddChannel(context.Context, *AddChannelReq) (*ViewChannelRes, error)
	ViewChannel(context.Context, *ChanReq) (*ViewChannelRes, error)
	ListChannel(context.Context, *EmptyReq) (*ListChannelRes, error)
	mustEmbedUnimplementedChannelServiceServer()
}

// UnimplementedChannelServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChannelServiceServer struct {
}

func (UnimplementedChannelServiceServer) AddChannel(context.Context, *AddChannelReq) (*ViewChannelRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddChannel not implemented")
}
func (UnimplementedChannelServiceServer) ViewChannel(context.Context, *ChanReq) (*ViewChannelRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewChannel not implemented")
}
func (UnimplementedChannelServiceServer) ListChannel(context.Context, *EmptyReq) (*ListChannelRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChannel not implemented")
}
func (UnimplementedChannelServiceServer) mustEmbedUnimplementedChannelServiceServer() {}

// UnsafeChannelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelServiceServer will
// result in compilation errors.
type UnsafeChannelServiceServer interface {
	mustEmbedUnimplementedChannelServiceServer()
}

func RegisterChannelServiceServer(s grpc.ServiceRegistrar, srv ChannelServiceServer) {
	s.RegisterService(&ChannelService_ServiceDesc, srv)
}

func _ChannelService_AddChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddChannelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).AddChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/channels.ChannelService/AddChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).AddChannel(ctx, req.(*AddChannelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_ViewChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).ViewChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/channels.ChannelService/ViewChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).ViewChannel(ctx, req.(*ChanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_ListChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).ListChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/channels.ChannelService/ListChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).ListChannel(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ChannelService_ServiceDesc is the grpc.ServiceDesc for ChannelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChannelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "channels.ChannelService",
	HandlerType: (*ChannelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddChannel",
			Handler:    _ChannelService_AddChannel_Handler,
		},
		{
			MethodName: "ViewChannel",
			Handler:    _ChannelService_ViewChannel_Handler,
		},
		{
			MethodName: "ListChannel",
			Handler:    _ChannelService_ListChannel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/channels.proto",
}
